# Generated by Django 5.0.7 on 2024-07-20 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Applieddate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='carrerprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentindustry', models.CharField(max_length=500)),
                ('department', models.CharField(max_length=500)),
                ('rolecategory', models.CharField(max_length=100)),
                ('jobtype', models.CharField(max_length=100)),
                ('employmenttype', models.CharField(max_length=100)),
                ('shift', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('expectedsalary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='educationmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('coursetype', models.CharField(max_length=100)),
                ('coursedurationstart', models.CharField(max_length=100)),
                ('coursedurationend', models.CharField(max_length=100)),
                ('gradingsystem', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentemployment', models.CharField(max_length=100)),
                ('employmenttype', models.CharField(max_length=100)),
                ('totalexperience', models.CharField(max_length=100)),
                ('currentcompanyname', models.CharField(max_length=100)),
                ('jobtitle', models.CharField(max_length=100)),
                ('joiningdate', models.DateField()),
                ('currentsalary', models.IntegerField()),
                ('skillsused', models.CharField(max_length=100)),
                ('jobprofile', models.CharField(max_length=100)),
                ('noticeperiod', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='jobupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(max_length=100)),
                ('JobDescription', models.CharField(max_length=500)),
                ('Requirements', models.CharField(max_length=500)),
                ('Additionalinformation', models.CharField(max_length=500)),
                ('Schedule', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=100)),
                ('employmenttype', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('contactemail', models.CharField(max_length=200)),
                ('companyname', models.CharField(max_length=200)),
                ('companylogo', models.ImageField(upload_to='image/')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Personaldetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=30)),
                ('martialstatus', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('diffrentlyabled', models.CharField(max_length=30)),
                ('careerbreak', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('hometown', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('languages', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Registeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('mobile', models.IntegerField(null=True)),
                ('workstatus', models.CharField(max_length=100, null=True)),
                ('currentcity', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appliedjob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobpic', models.ImageField(upload_to='')),
                ('companyname', models.CharField(max_length=200)),
                ('jobtitle', models.CharField(max_length=200)),
                ('jobstatus', models.CharField(max_length=100)),
                ('apply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobspireapp.applies')),
            ],
        ),
        migrations.CreateModel(
            name='applyitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobspireapp.jobupload')),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='pdf/')),
                ('resumeheadline', models.CharField(max_length=200)),
                ('keyskills', models.CharField(max_length=200)),
                ('projects', models.CharField(max_length=100)),
                ('profilesummary', models.CharField(max_length=100, null=True)),
                ('profilepic', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('carrerprofile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobspireapp.carrerprofile')),
                ('educationdetails', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobspireapp.educationmodel')),
                ('employmentdetails', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobspireapp.employment')),
                ('personaldetails', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobspireapp.personaldetails')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobspireapp.registeration')),
            ],
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobspireapp.registeration'),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('cover_letter', models.CharField(max_length=500)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobspireapp.jobupload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobspireapp.registeration')),
            ],
        ),
        migrations.AddField(
            model_name='employment',
            name='register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobspireapp.registeration'),
        ),
        migrations.AddField(
            model_name='educationmodel',
            name='register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobspireapp.registeration'),
        ),
        migrations.AddField(
            model_name='carrerprofile',
            name='register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobspireapp.registeration'),
        ),
        migrations.AddField(
            model_name='applies',
            name='userdetails',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobspireapp.registeration'),
        ),
        migrations.CreateModel(
            name='savejob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('saved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobspireapp.jobupload')),
            ],
        ),
    ]
